server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**, /user/**, /booking/**
          filters:
            - RewritePath=/api/bookings/(?<segment>.*), /$\{segment}

        - id: hotel-service
          uri: lb://hotel-service
          predicates:
            - Path=/api/hotels/**, /api/rooms/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
