server:
  port: 8081

spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:h2:mem:bookingdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # Заглушка:
          jwk-set-uri: http://localhost:9999/real-jwk  # временно, чтобы контекст поднялся


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
