server:
  port: 8082

spring:
  application:
    name: booking-service

  datasource:
    url: jdbc:h2:mem:bookingdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: your-secret-key-minimum-256-bits-long-for-hs256-algorithm
  expiration: 3600000

hotel-service:
  url: http://hotel-service
