server:
  port: 8081

spring:
  application:
    name: hotel-service

  datasource:
    url: jdbc:h2:mem:hoteldb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: your-secret-key-minimum-256-bits-long-for-hs256-algorithm
  expiration: 3600000
